// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: matchmaking.proto

package simple_mm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MatchmakingServiceClient is the client API for MatchmakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchmakingServiceClient interface {
	AddMatchmaking(ctx context.Context, in *MatchmakingRequest, opts ...grpc.CallOption) (*MatchmakingResponse, error)
	AddFakeUser(ctx context.Context, in *MatchmakingRequest, opts ...grpc.CallOption) (*MatchmakingResponse, error)
}

type matchmakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakingServiceClient(cc grpc.ClientConnInterface) MatchmakingServiceClient {
	return &matchmakingServiceClient{cc}
}

func (c *matchmakingServiceClient) AddMatchmaking(ctx context.Context, in *MatchmakingRequest, opts ...grpc.CallOption) (*MatchmakingResponse, error) {
	out := new(MatchmakingResponse)
	err := c.cc.Invoke(ctx, "/user.MatchmakingService/AddMatchmaking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) AddFakeUser(ctx context.Context, in *MatchmakingRequest, opts ...grpc.CallOption) (*MatchmakingResponse, error) {
	out := new(MatchmakingResponse)
	err := c.cc.Invoke(ctx, "/user.MatchmakingService/AddFakeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchmakingServiceServer is the server API for MatchmakingService service.
// All implementations must embed UnimplementedMatchmakingServiceServer
// for forward compatibility
type MatchmakingServiceServer interface {
	AddMatchmaking(context.Context, *MatchmakingRequest) (*MatchmakingResponse, error)
	AddFakeUser(context.Context, *MatchmakingRequest) (*MatchmakingResponse, error)
	mustEmbedUnimplementedMatchmakingServiceServer()
}

// UnimplementedMatchmakingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMatchmakingServiceServer struct {
}

func (UnimplementedMatchmakingServiceServer) AddMatchmaking(context.Context, *MatchmakingRequest) (*MatchmakingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMatchmaking not implemented")
}
func (UnimplementedMatchmakingServiceServer) AddFakeUser(context.Context, *MatchmakingRequest) (*MatchmakingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFakeUser not implemented")
}
func (UnimplementedMatchmakingServiceServer) mustEmbedUnimplementedMatchmakingServiceServer() {}

// UnsafeMatchmakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakingServiceServer will
// result in compilation errors.
type UnsafeMatchmakingServiceServer interface {
	mustEmbedUnimplementedMatchmakingServiceServer()
}

func RegisterMatchmakingServiceServer(s grpc.ServiceRegistrar, srv MatchmakingServiceServer) {
	s.RegisterService(&MatchmakingService_ServiceDesc, srv)
}

func _MatchmakingService_AddMatchmaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).AddMatchmaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.MatchmakingService/AddMatchmaking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).AddMatchmaking(ctx, req.(*MatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_AddFakeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).AddFakeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.MatchmakingService/AddFakeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).AddFakeUser(ctx, req.(*MatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchmakingService_ServiceDesc is the grpc.ServiceDesc for MatchmakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchmakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.MatchmakingService",
	HandlerType: (*MatchmakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMatchmaking",
			Handler:    _MatchmakingService_AddMatchmaking_Handler,
		},
		{
			MethodName: "AddFakeUser",
			Handler:    _MatchmakingService_AddFakeUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchmaking.proto",
}
